### ISSUE TITLE
Create separate mailing list for virtual and in-person participants

### ISSUE THREAD

**Issue by dzhlobo** [birs-math/workshops#8]
For member of an event we have maillists.

<img width="1734" alt="Screenshot 2023-01-13 at 12 22 11" src="https://user-images.githubusercontent.com/800337/212309413-b80f7260-138f-4807-a98a-c280f261ca87.png">

Administrator would like to have separate maillists for those who attend in person and those who attend online. I think it's still would be beneficial to have one maillist with all the attendees and 2 more: online and offline attendees.

I'm not sure yet how maillists work but we'll have to figure it out.

**Comment by birs-math** [comment]
Maybe there is a way to sort or select **in person** vs **online** vs **organizers only** vs **all**. 

Really not sure but I can ask the team what they wish

**Comment by birs-math** [comment]
Instead of creating an email address to send to, I have a feeling its outside of the control and scope of the workshops application to create and send to distributions lists held in other BIRS infrastructure. We would be fine to have new pages and email templates created in the left hand NAV bar for these common tasks. Mock up [attached.]
<img width="378" alt="Screen Shot 2023-01-13 at 9 52 55 AM" src="https://user-images.githubusercontent.com/77022197/212388218-126fa32f-da0a-411b-8ebe-6aedc6fba031.png">

**Comment by birs-math** [comment]
https://github.com/birs-math/workshops/pull/18

**Comment by birs-math** [comment]
PR merged to PROD
